uploaded
siCss
	^ '
body {
 
font: normal 100% Arial, Helvetica, Verdana, sans-serif;
}
 

.generic {
 
font-family: Geneva, Arial, Helvetica, sans-serif;
 
font-style: normal;
 
font-weight: normal;
 
font-size: 14px;
 
color : #663300;
 
padding: 20px;
 
margin-top: 20px;
 
margin-left: 20px;
 
border: 1px solid #663300;
 
width: 500px;
}

.lightbox {
 
background-color:#FFFFFF;
}

.errorMessage {
 
background-color: #ffb0b0;
 
border: 1px solid #ee0000;
 
padding: 5px;
 
margin-bottom: 10px;
}

.infoMessage {
 
background-color: #fbffcc;
 
border: 1px solid #eda33a;
 
padding: 5px;
 
margin-bottom: 10px;
}

.copyright {
 
font-family: Geneva, Arial, Helvetica, sans-serif;
 
font-size: 10px;
 
font-style: normal;
 
font-weight: normal;
 
color: #663300;
 
text-align: left;
 
margin-left: 20px;
}

a {
 
color : #663300;
 
text-decoration: underline;
}'